name: Lint

on:
  [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Installing Front End Dependencies
      working-directory: ./comeback-world
      run: npm ci

    - name: Front End Linter
      working-directory: ./comeback-world
      run: npx eslint ./src --ext .js
        
    - name: Installing Back End Dependencies
      working-directory: ./api
      run: npm ci
    
    - name: Backend Linter
      working-directory: ./api
      run: npx eslint . --ext .js